orthrus:
  http:
    connect-timeout-ms: 5000
    read-timeout-ms: 10000
    max-redirects: 5
    ignore-ssl-errors: false

  scan:
    concurrency: 10
    include-scanners: []
    exclude-scanners: []

  report:
    default-format: json # json, sarif, html, console

  discovery:
    blackbox-max-depth: 5
    blackbox-timeout-ms: 5000

server:
  port: 8080

spring:
  messages:
    basename: messages
    fallback-to-system-locale: false
  r2dbc:
    url: r2dbc:h2:file:///./orthrus_db/data;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  main:
    web-application-type: reactive
