server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

orthrus:
  master:
    url: http://localhost:8080
    internal-token: "change-me-in-production"
    slave-timeout-seconds: 30
    offline-slave-deletion-minutes: 15
  slave:
    advertised-url: http://not-used
  security:
    admin:
      username: ${ADMIN_USERNAME:superadmin}
      password: ${ADMIN_PASSWORD:superadmin}

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  r2dbc:
    url: r2dbc:h2:file:///./orthrus_db/data;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: ""
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  main:
    web-application-type: reactive
  codec:
    max-in-memory-size: 50MB
  messages:
    fallback-to-system-locale: false

logging:
  level:
    org.apache.pdfbox.pdmodel.font.PDType1Font: ERROR
